#!/usr/bin/env bash
# One-time setup of InventoryTracker on a fresh Ubuntu 22.04/24.04 (or Debian 12) server.
#
#   curl -fsSL https://raw.githubusercontent.com/DanTransfat/InventoryTracker/main/deploy/setup-vm.sh | sudo bash
#
# Optional environment variables (put them after `sudo`, e.g. `sudo DOMAIN=inv.example.com bash`):
#   DOMAIN    your own hostname whose DNS A record points at this server.
#             Default: <public-ip>.sslip.io, a free hostname that resolves to your IP,
#             so you get real HTTPS with no domain to buy or configure.
#   REPO_URL  git repository to deploy (default: this project's GitHub repo)
#   APP_DIR   where to put it (default: /opt/inventory-tracker)
#
# Safe to run again: it skips anything already done and never overwrites .env.
set -euo pipefail

# Everything is inside main() so bash reads the whole script before running any of it.
# That matters for `curl ... | sudo bash`: otherwise a command that reads stdin could
# swallow the rest of the script.
main() {

REPO_URL="${REPO_URL:-https://github.com/DanTransfat/InventoryTracker.git}"
APP_DIR="${APP_DIR:-/opt/inventory-tracker}"
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.prod.yml)

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mError: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run this with sudo (it installs Docker and opens firewall ports)."
command -v apt-get >/dev/null || die "this script expects Ubuntu or Debian."

say "1/6 Installing Docker, git and curl"
apt-get update -qq
apt-get install -y -qq git curl ca-certificates openssl >/dev/null
if ! command -v docker >/dev/null; then
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null || die "Docker Compose plugin is missing."
systemctl enable --now docker >/dev/null 2>&1 || true

say "2/6 Adding swap if this server has under 2 GB of memory"
# MySQL plus building the frontend can exceed 1 GB; swap prevents out-of-memory kills.
mem_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
if [ "$mem_kb" -lt 2000000 ] && [ -z "$(swapon --show --noheadings)" ]; then
  fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048 status=none
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  echo "Added a 2 GB swap file."
else
  echo "Not needed."
fi

say "3/6 Opening ports 22 (SSH), 80 and 443 in the server firewall"
if command -v ufw >/dev/null; then
  ufw allow OpenSSH >/dev/null
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw allow 443/udp >/dev/null
  ufw --force enable >/dev/null
  ufw status | sed -n '1,12p'
else
  echo "ufw not installed; relying on your cloud provider's firewall."
fi

say "4/6 Getting the code into $APP_DIR"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull --ff-only
else
  git clone --depth 1 "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

say "5/6 Writing .env with random passwords"
if [ -f .env ]; then
  echo ".env already exists; keeping it."
else
  public_ip=$(curl -fsS --max-time 10 https://api.ipify.org || curl -fsS --max-time 10 https://ifconfig.me || true)
  if [ -z "${DOMAIN:-}" ]; then
    [ -n "$public_ip" ] || die "could not detect the public IP. Re-run with DOMAIN=<hostname>."
    DOMAIN="$(echo "$public_ip" | tr '.' '-').sslip.io"
  fi
  umask 077
  cat > .env <<EOF
# Generated by deploy/setup-vm.sh on $(date -u +%Y-%m-%dT%H:%MZ). Keep this file private.
SITE_ADDRESS=$DOMAIN
MYSQL_ROOT_PASSWORD=$(openssl rand -hex 24)
MYSQL_DATABASE=inventory
MYSQL_USER=inventory
MYSQL_PASSWORD=$(openssl rand -hex 24)
LOG_LEVEL=INFO
ALERT_NOTIFIER=log
EOF
  echo "Site address: $DOMAIN"
fi
site=$(grep '^SITE_ADDRESS=' .env | cut -d= -f2-)

say "6/6 Building and starting (first build takes 3-8 minutes)"
"${COMPOSE[@]}" up -d --build

echo "Waiting for the app to answer..."
for _ in $(seq 1 60); do
  if curl -fsS --max-time 3 http://127.0.0.1:8080/api/health >/dev/null 2>&1; then
    "${COMPOSE[@]}" ps
    cat <<EOF

InventoryTracker is running.

  Open:    https://$site
  (The first visit can take up to a minute while the HTTPS certificate is issued.)

  Logs:    cd $APP_DIR && ${COMPOSE[*]} logs -f
  Update:  sudo $APP_DIR/deploy/update.sh
EOF
    exit 0
  fi
  sleep 5
done
"${COMPOSE[@]}" ps
"${COMPOSE[@]}" logs --tail=50
die "the app did not become healthy within 5 minutes. The logs above usually say why."
}

main "$@"
